image: node:latest

stages:
  - build
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

build_frontend:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - ./frontend/build
    expire_in: 10 minutes
  only:
    - stage

deploy_to_s3_stage:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - ls ./frontend
    - aws s3 sync --delete ./frontend/build s3://$AWS_STAGING_S3 
  only:
    - stage
