image: node:latest

stages:
  - build
  - backend-tests
  - deploy

build_frontend:
  stage: build
  image: node:15.8.0

  cache:
    paths:
      - ./frontend/node_modules
  script:
    - cd frontend
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - ./frontend/build
    expire_in: 10 minutes
  only:
    - stage

deploy_to_s3_stage:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws s3 sync --delete ./frontend/build s3://$AWS_STAGING_S3
  only:
    - stage

deploy_to_heroku:
  stage: deploy
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - cd backend
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - stage

backend_tests:
  stage: backend-tests
  image: python:3.6.2
  before_script:
    - cd backend
    - pip install -r requirements.txt
  script:
    - python manage.py test
  only:
    - merge_requests

