image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - deploy

staging:
  stage: deploy
  image: ruby:latest
  script:
    - cd frontend
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - stage # Will run only on the staging branch
