image: node:latest

stages:
  - build
  - deploy
  - backend-tests

build_frontend:
  stage: build
  image: node:latest

  cache:
    paths:
      - ./frontend/node_modules
  script:
    - cd frontend
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - ./frontend/build
    expire_in: 10 minutes
  only:
    - stage

deploy_to_s3_stage:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws s3 sync --delete ./frontend/build s3://$AWS_STAGING_S3 
  only:
    - stage

backend_tests:
  stage: backend-tests
  image: python:3.6.2
  before_script:
    - cd backend
    - pip install -r requirements.txt
  script:
    - python manage.py test
  only:
    - merge_requests

