swagger: '2.0'
info:
  title: v2.0 Documentation
  description: Swagger Specification
  version: v2
host: 127.0.0.1:8000
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /analytics/event:
    post:
      operationId: analytics_event_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Event'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Event'
      tags:
        - analytics
    parameters: []
  /api/categories:
    get:
      operationId: api_categories_list
      description: ''
      parameters:
        - name: ids
          in: query
          description: Categories ids separated by commas
          type: array
          items:
            type: integer
        - name: parent_topic_is_null
          in: query
          description: ''
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
      tags:
        - api
    parameters: []
  /api/categories/{id}:
    get:
      operationId: api_categories_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Category'
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this category.
        required: true
        type: integer
  /api/categories/{id}/related_expressions:
    get:
      operationId: api_categories_related_expressions
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Expression'
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this category.
        required: true
        type: integer
  /api/expressions:
    get:
      operationId: api_expressions_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Expression'
      tags:
        - api
    post:
      operationId: api_expressions_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Expression'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Expression'
      tags:
        - api
    parameters: []
  /api/expressions/{id}:
    get:
      operationId: api_expressions_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Expression'
      tags:
        - api
    put:
      operationId: api_expressions_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Expression'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Expression'
      tags:
        - api
    patch:
      operationId: api_expressions_partial_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Expression'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Expression'
      tags:
        - api
    delete:
      operationId: api_expressions_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this expression.
        required: true
        type: integer
  /api/expressions/{id}/related_categories:
    get:
      operationId: api_expressions_related_categories
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this expression.
        required: true
        type: integer
  /api/mnemonicTypes:
    get:
      operationId: api_mnemonicTypes_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/MnemonicType'
      tags:
        - api
    post:
      operationId: api_mnemonicTypes_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/MnemonicType'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/MnemonicType'
      tags:
        - api
    parameters: []
  /api/mnemonicTypes/{id}:
    get:
      operationId: api_mnemonicTypes_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/MnemonicType'
      tags:
        - api
    put:
      operationId: api_mnemonicTypes_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/MnemonicType'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/MnemonicType'
      tags:
        - api
    patch:
      operationId: api_mnemonicTypes_partial_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/MnemonicType'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/MnemonicType'
      tags:
        - api
    delete:
      operationId: api_mnemonicTypes_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this mnemonic type.
        required: true
        type: integer
  /api/mnemonics:
    get:
      operationId: api_mnemonics_list
      description: ''
      parameters:
        - name: search
          in: query
          description: A search term.
          required: false
          type: string
        - name: tags
          in: query
          description: Tags ids separated by commas
          type: array
          items:
            type: integer
        - name: types
          in: query
          description: Mnemonic types ids separated by commas
          type: array
          items:
            type: integer
        - name: ids
          in: query
          description: Mnemonic ids separated by commas
          type: array
          items:
            type: integer
        - name: limit
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
        - name: offset
          in: query
          description: The initial index from which to return the results.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Mnemonic'
      tags:
        - api
    post:
      operationId: api_mnemonics_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Mnemonic'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Mnemonic'
      tags:
        - api
    parameters: []
  /api/mnemonics/{id}:
    get:
      operationId: api_mnemonics_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Mnemonic'
      tags:
        - api
    put:
      operationId: api_mnemonics_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Mnemonic'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Mnemonic'
      tags:
        - api
    patch:
      operationId: api_mnemonics_partial_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Mnemonic'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Mnemonic'
      tags:
        - api
    delete:
      operationId: api_mnemonics_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this mnemonic.
        required: true
        type: integer
  /api/tags:
    get:
      operationId: api_tags_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Tag'
      tags:
        - api
    parameters: []
  /api/tags/{id}:
    get:
      operationId: api_tags_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Tag'
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this tag.
        required: true
        type: integer
definitions:
  Event:
    required:
      - datetime
      - eventType
    type: object
    properties:
      datetime:
        title: Datetime
        type: string
        format: date-time
      data:
        title: Data
        type: object
        x-nullable: true
      eventType:
        title: EventType
        type: string
        enum:
          - MV
  Category:
    required:
      - title
      - child_topics
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      title:
        title: Title
        type: string
        minLength: 1
      parent_topic:
        title: Parent topic
        type: integer
        x-nullable: true
      child_topics:
        type: array
        items:
          type: integer
        uniqueItems: true
      expressions:
        type: array
        items:
          type: integer
        uniqueItems: true
      tags:
        type: array
        items:
          type: integer
        uniqueItems: true
  Expression:
    required:
      - title
      - mnemonics
      - categories
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      title:
        title: Title
        type: string
        minLength: 1
      description:
        title: Description
        type: string
        x-nullable: true
      mnemonics:
        type: array
        items:
          type: integer
        uniqueItems: true
      categories:
        type: array
        items:
          type: integer
        uniqueItems: true
      tags:
        type: array
        items:
          type: integer
        uniqueItems: true
  MnemonicType:
    required:
      - label
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      label:
        title: Label
        type: string
        maxLength: 256
        minLength: 1
      mnemonics:
        type: array
        items:
          type: integer
        uniqueItems: true
  Mnemonic:
    required:
      - title
      - types
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      title:
        title: Title
        type: string
        minLength: 1
      description:
        title: Description
        type: string
        x-nullable: true
      expression:
        title: Expression
        type: integer
        x-nullable: true
      source_url:
        title: Source url
        type: string
        format: uri
        maxLength: 2000
        x-nullable: true
      links:
        type: array
        items:
          title: Links
          type: string
          format: uri
          maxLength: 2000
          minLength: 1
        x-nullable: true
      types:
        type: array
        items:
          type: integer
        uniqueItems: true
      tags:
        type: array
        items:
          type: integer
        uniqueItems: true
  Tag:
    required:
      - label
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      label:
        title: Label
        type: string
        maxLength: 256
        minLength: 1
