/* tslint:disable */
/* eslint-disable */
/**
 * v2.0 Documentation
 * Swagger Specification
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    datetime: Date;
    /**
     * 
     * @type {object}
     * @memberof Event
     */
    data?: object | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    eventType: EventEventTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum EventEventTypeEnum {
    Mv = 'MV'
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datetime': (new Date(json['datetime'])),
        'data': !exists(json, 'data') ? undefined : json['data'],
        'eventType': json['eventType'],
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datetime': (value.datetime.toISOString()),
        'data': value.data,
        'eventType': value.eventType,
    };
}


