/* tslint:disable */
/* eslint-disable */
/**
 * v2.0 Documentation
 * Swagger Specification
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Expression
 */
export interface Expression {
    /**
     * 
     * @type {number}
     * @memberof Expression
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Expression
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Expression
     */
    description?: string | null;
    /**
     * 
     * @type {Set<number>}
     * @memberof Expression
     */
    mnemonics: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof Expression
     */
    categories: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof Expression
     */
    tags: Set<number>;
}

export function ExpressionFromJSON(json: any): Expression {
    return ExpressionFromJSONTyped(json, false);
}

export function ExpressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Expression {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'mnemonics': json['mnemonics'],
        'categories': json['categories'],
        'tags': json['tags'],
    };
}

export function ExpressionToJSON(value?: Expression | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'mnemonics': value.mnemonics,
        'categories': value.categories,
        'tags': value.tags,
    };
}


