/* tslint:disable */
/* eslint-disable */
/**
 * v2.0 Documentation
 * Swagger Specification
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpressionUpdate
 */
export interface ExpressionUpdate {
    /**
     * 
     * @type {string}
     * @memberof ExpressionUpdate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ExpressionUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExpressionUpdate
     */
    categories: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExpressionUpdate
     */
    tags: Array<number>;
}

export function ExpressionUpdateFromJSON(json: any): ExpressionUpdate {
    return ExpressionUpdateFromJSONTyped(json, false);
}

export function ExpressionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpressionUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'categories': json['categories'],
        'tags': json['tags'],
    };
}

export function ExpressionUpdateToJSON(value?: ExpressionUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'categories': value.categories,
        'tags': value.tags,
    };
}


