/* tslint:disable */
/* eslint-disable */
/**
 * v2.0 Documentation
 * Swagger Specification
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleSocialAuth
 */
export interface GoogleSocialAuth {
    /**
     * 
     * @type {string}
     * @memberof GoogleSocialAuth
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof GoogleSocialAuth
     */
    redirectUri: string;
}

export function GoogleSocialAuthFromJSON(json: any): GoogleSocialAuth {
    return GoogleSocialAuthFromJSONTyped(json, false);
}

export function GoogleSocialAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleSocialAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'redirectUri': json['redirect_uri'],
    };
}

export function GoogleSocialAuthToJSON(value?: GoogleSocialAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'redirect_uri': value.redirectUri,
    };
}


