/* tslint:disable */
/* eslint-disable */
/**
 * v2.0 Documentation
 * Swagger Specification
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MnemonicType
 */
export interface MnemonicType {
    /**
     * 
     * @type {number}
     * @memberof MnemonicType
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof MnemonicType
     */
    label: string;
    /**
     * 
     * @type {Set<number>}
     * @memberof MnemonicType
     */
    mnemonics?: Set<number>;
}

export function MnemonicTypeFromJSON(json: any): MnemonicType {
    return MnemonicTypeFromJSONTyped(json, false);
}

export function MnemonicTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MnemonicType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': json['label'],
        'mnemonics': !exists(json, 'mnemonics') ? undefined : json['mnemonics'],
    };
}

export function MnemonicTypeToJSON(value?: MnemonicType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'mnemonics': value.mnemonics,
    };
}


