/* tslint:disable */
/* eslint-disable */
/**
 * v2.0 Documentation
 * Swagger Specification
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Register
 */
export interface Register {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof Register
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    fullname: string;
    /**
     * 
     * @type {string}
     * @memberof Register
     */
    email: string;
}

export function RegisterFromJSON(json: any): Register {
    return RegisterFromJSONTyped(json, false);
}

export function RegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'fullname': json['fullname'],
        'email': json['email'],
    };
}

export function RegisterToJSON(value?: Register | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'fullname': value.fullname,
        'email': value.email,
    };
}


