# Generated by Django 3.1.7 on 2021-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnemonics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='mnemonics.Tag'),
        ),
        migrations.AddField(
            model_name='expression',
            name='tags',
            field=models.ManyToManyField(related_name='expressions', to='mnemonics.Tag'),
        ),
        migrations.AddField(
            model_name='mnemonic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mnemonics', to='mnemonics.Tag'),
        ),
    ]
