# Generated by Django 3.1.7 on 2021-04-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnemonics', '0002_auto_20210415_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='expressions',
            field=models.ManyToManyField(blank=True, related_name='categories', to='mnemonics.Expression'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_topics', to='mnemonics.category'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expressions', to='mnemonics.Tag'),
        ),
        migrations.AlterField(
            model_name='mnemonic',
            name='expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mnemonics', to='mnemonics.expression'),
        ),
        migrations.AlterField(
            model_name='mnemonictype',
            name='mnemonics',
            field=models.ManyToManyField(blank=True, related_name='types', to='mnemonics.Mnemonic'),
        ),
    ]
