# Generated by Django 3.2.4 on 2021-07-13 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mnemonics', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expression',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expression',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mnemonic',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mnemonic',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
