name: Mnemonics Code Checking

on:
  pull_request:
    branches:
      - master
jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v2
    - name: run backend
      run: |
        cd backend
        pip install -r requirements.txt
        python manage.py test
  check-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - uses: actions/checkout@v2
    - run: yarn policies set-version 1.22.5
    - name: run frontend
      run: |
        cd frontend
        yarn install
        yarn run lint

