name: Mnemonics Deployment

on:
  push:
    branches:
      - master
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy backend
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_STAGING }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "backend"
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - run: yarn policies set-version 1.22.5
    - run: |
        cd frontend
        yarn install
        yarn run build
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./frontend/build s3://${{ secrets.AWS_S3_BUCKET_STAGING }} --delete

